### ISSUE TITLE
Changes in Firebase visability

### ISSUE THREAD

**Issue by MikKrak** [peterfriese/BookSpine#5]
Thank you Peter for very good sample of the SwiftUI + FireBase project. Everything is working fine, but I, as newer in FB and SwiftUI, still can't understand why we can see changes, made in FB console, when we are in BookDetailView ?

BookListView has observable  viewModel, which is synchronized with FB. But BookListView passes to BookDetailView ‘book’ instance from ForEach closure. What is «book» passed to BookDetailView in this case? Isn't it just "let" constant, not connected to FB? Why it changes inside  BookDetailView when data changes in FB console?

Moreover, BookDetailView passes it further to BookEditView without any binding and it also stays synchronized with FB in there. How all these 3 "book" ( book in BookListViewModel as [books] item, book in BookDetailView as just "var book:Book" and book in BookEditView) are connected? Are they the same instance ob Book class?

Another small but important thing regards your 3 "Book" project posts. They are very useful and clear, but in some places are not synchronized with your code and with each other. For example in Post1 you still have "fetch" method in BookListViewModel while in Part 4(https://peterfriese.dev/swiftui-firebase-update-data/) and in the code you have already "subscribe" and "unsubscribe" methods.  As your posts, as I said, are very useful and may be unic for the topic, it's very important to make them perfect and to remove small disadvantages.
Thank you in advance for your help!

**Comment by brenner-tobias** [comment]
I would like to extend this question with the following: How are you "dismissing" the changes in the Book in the BookEditView when clicking the "Cancel" Button? My understanding from your code would be that the changes are still in the object but just not stored to Firebase, meaning they would show up again when clicking on the Edit button again. For that reason, I am using a "draftBook" in another application I am building, but it looks like it is working for you without that, which I cannot reproduce in my app or understand in yours.
Thanks a lot for your reply.
